security:
    encoders:
#        LdapTools\Bundle\LdapToolsBundle\Security\User\LdapUser: plaintext
        AppBundle\Entity\User: bcrypt
    providers:
#        chain_provider:
#            chain:
#                providers: [ db, ldap ]
        db:
            entity:
                class: AppBundle:User
                property: username
#        ldap:
#            id: ldap_tools.security.user.ldap_user_provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login_check
            stateless: true
            anonymous: true
            form_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern:   ^/
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
