services:
    app.manager.feature:
        class: AppBundle\Manager\FeatureManager
        arguments:
            - "@filesystem"
            - "%deploys_root_dir%"
            - "%projects_root_dir%"
            - "@slugify"
            - "@app.parser.feature"
            - "@app.transformer.feature_to_string"
            - "@app.manager.project"
            - "@app.parser.test_result"
    app.manager.project:
        class: AppBundle\Manager\ProjectManager
        arguments:
            - "@filesystem"
            - "%projects_root_dir%"
            - "%deploys_root_dir%"
            - "@slugify"
            - "@app.parser.feature"
            - "@app.utils.git"
